name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions: read-all

jobs:
  ci:
    uses: h13/.github/.github/workflows/ci-node.yml@v1

  codecov:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: pnpm/action-setup@02f6c237bd2518259fed6c71566509edfb3f2b74 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: package.json
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
      - uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad # v5
        with:
          files: coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
