name: Publish

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  publish:
    uses: h13/.github/.github/workflows/publish-node.yml@1deeb7c9449b3f6e2069ee7c2e9b348effef8469 # main
    secrets: inherit
