name: Publish

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  publish:
    uses: h13/.github/.github/workflows/publish-node.yml@046130b2b6587f6b6b02c120a977bcd9029df7b2 # main
    secrets: inherit
