name: Publish

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  publish:
    uses: h13/.github/.github/workflows/publish-node.yml@80293c892bc5ca0b5db8945512edab3c9dd3f81f # main
    secrets: inherit
